### PR TITLE
fix: if one arch platform doesn't exists for mod, do not write db/smod for that modarch

### PR DESCRIPTION
**Pull request by porisius**
Reference #smr-api: https://discord.com/channels/555424930502541343/830842478956642354/1064329342668255315

### CODE REVIEW

**Comment by porisius** [comment]
Based on this evidence:
image

**Comment by Vilsol** [comment]
I would rather want to actually load the zip file and check its contents rather than rely purely on file size, please make it test whether there is a valid uplugin inside all of them.

**Comment by porisius** [comment]
That's a more logical solution, I think can reuse some of the currently used validation functions for that as well.

**Comment by porisius** [comment]
Disregard, appears my fork got messed up... closing PR for now.

**Pull request closed without merging**
